name: Build DirectXHook DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Проверяем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Устанавливаем MSBuild и Visual Studio Build Tools
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Устанавливаем DirectX SDK (загружаем и распаковываем)
    - name: Download and install DirectX SDK
      run: |
        curl -L -o dxsdk.exe "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-1A1BB54D85C6/DXSDK_Jun10.exe"
        .\dxsdk.exe /quiet /norestart /dir:"C:\DXSDK"
      shell: cmd

    # Настраиваем переменную окружения для DirectX SDK
    - name: Set DirectX SDK environment variable
      run: echo "DXSDK_DIR=C:\DXSDK\" >> $env:GITHUB_ENV
      shell: powershell

    # Компилируем проект с помощью MSBuild
    - name: Build with MSBuild
      run: msbuild DirectXHook.vcxproj /p:Configuration=Release /p:Platform=Win32 /t:Build

    # Загружаем артефакт (собранную DLL)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DirectXHook-DLL
        path: Release/DirectXHook.dll
