# Имя нашего рабочего процесса
name: Build Translator DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Запускаем на виртуальной машине с последней версией Windows
    runs-on: windows-latest

    steps:
    # 1. Клонируем репозиторий вместе с нашими файлами SDK
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Настройка окружения для компиляции MSVC x86
    # Этот шаг добавляет компилятор cl.exe и другие утилиты в PATH
    - name: Add MSVC to PATH
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    # 3. Компиляция DLL с использованием локальных файлов SDK
    # Мы больше не скачиваем SDK, а указываем компилятору пути к папке /vendor
    - name: Compile the DLL
      run: |
        cl.exe /LD /nologo /O2 /MT /D "WIN32" /D "NDEBUG" /D "_WINDOWS" /D "_USRDLL" `
          /I"vendor/dxsdk/Include" `
          /link /LIBPATH:"vendor/dxsdk/Lib/x86" `
          /Fe:translator.dll `
          translator.cpp
      shell: cmd

    # 4. Загрузка артефакта (скомпилированной DLL и файла перевода)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: translator-release
        path: |
          translator.dll
          translations.txt
