name: Build DirectXHook DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Проверяем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Устанавливаем MSBuild и Visual Studio Build Tools
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Загружаем и сразу устанавливаем DirectX SDK
    - name: Download and install DirectX SDK
      run: |
        powershell -Command "Invoke-WebRequest -Uri 'http://null22.cefmt.no.eu.org/dxsdk.exe' -OutFile 'dxsdk.exe'; Start-Process -FilePath '.\dxsdk.exe' -ArgumentList '/quiet /norestart /dir:\"C:\DXSDK\"' -NoNewWindow -Wait"
      shell: cmd

    # Настраиваем переменную окружения для DirectX SDK
    - name: Set DirectX SDK environment variable
      run: echo "DXSDK_DIR=C:\DXSDK\" >> $env:GITHUB_ENV
      shell: powershell

    # Компилируем проект с помощью MSBuild
    - name: Build with MSBuild
      run: msbuild DirectXHook.vcxproj /p:Configuration=Release /p:Platform=Win32 /t:Build

    # Загружаем артефакт (собранную DLL)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DirectXHook-DLL
        path: Release/DirectXHook.dll
